### ISSUE TITLE
The meaning of .._esm_id.npy

### ISSUE THREAD

**Issue by xinghao302001** [Hhhzj-7/DeepFusionGO#1]
Hello, 
Thanks for your research, but I do not understand the meaning of these files in your data file such as bp_test_esm_id.npy. I want to ask what the meaning of these files is(.._esm_id.npy). Thanks

Best regards,
Xinghao

**Comment by xinghao302001** [comment]
Another question: if I want to use other pre-trained protein LMs to encode protein sequences in the experiment rather than only using ESM-1b, how could I do so that I can continue to use your other parts of codes?
Xinghao

**Comment by Hhhzj-7** [comment]
> 
Thanks for your question. These files are not final requirements. We have updated the relevant documents in the repository.

**Comment by Hhhzj-7** [comment]
> 
If you want to use other pre-trained protein LMs to encode protein sequences and continue to use other parts of codes,  you can refer to "/deepfusiongo/architecture.py".
